Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

AllCops:
  UseCache: false
