default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: 127.0.0.1

development:
  <<: *default
  database: finance_control_development
  port: <%= ENV["PGPORT"] || 5432 %>

test:
  <<: *default
  database: finance_control_test
  port: <%= ENV["PGPORT"] || 5432 %>

production:
  <<: *default
  database: finance_control_production
  username: finance_control
  password: <%= ENV["FINANCE_CONTROL_DATABASE_PASSWORD"] %>
